//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evergine.MRTK.Effects
{
    using Evergine.Framework.Graphics;


    [Evergine.Framework.Graphics.MaterialDecoratorAttribute("4f7e4c24-e83c-4350-9cd4-511fb2199cf4")]
    public partial class HoloGraphic : Evergine.Framework.Graphics.MaterialDecorator
    {

        public HoloGraphic(Evergine.Framework.Graphics.Effects.Effect effect) :
                this(new Material(effect))
        {
        }

        public HoloGraphic(Evergine.Framework.Graphics.Material material) :
                base(material)
        {
            this.EnsureIsHolographic(material?.Effect);
        }

        public Evergine.Mathematics.Vector3 Parameters_Color
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector3>(0);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 0);
            }
        }

        public float Parameters_Alpha
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(12);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 12);
            }
        }

        public Evergine.Mathematics.Vector3 Parameters_InnerGlowColor
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector3>(16);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 16);
            }
        }

        public float Parameters_InnerGlowAlpha
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(28);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 28);
            }
        }

        public float Parameters_InnerGlowPower
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(32);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 32);
            }
        }

        public float Parameters_BorderWidth
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(36);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 36);
            }
        }

        public float Parameters_BorderMinValue
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(40);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 40);
            }
        }

        public float Parameters_FluentLightIntensity
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(44);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 44);
            }
        }

        public float Parameters_RoundCornerRadious
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(48);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 48);
            }
        }

        public float Parameters_RoundCornerMargin
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(52);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 52);
            }
        }

        public float Parameters_Cutoff
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(56);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 56);
            }
        }

        public Evergine.Mathematics.Vector4 Parameters_RoundCornersRadious
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector4>(64);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 64);
            }
        }

        public float Parameters_EdgeSmoothingValue
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(60);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 60);
            }
        }

        public float Parameters_FadeBeginDistance
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(80);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 80);
            }
        }

        public float Parameters_FadeCompleteDistance
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(84);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 84);
            }
        }

        public float Parameters_FadeMinValue
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(88);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 88);
            }
        }

        public Evergine.Mathematics.Vector3 Parameters_HoverColorOverride
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector3>(96);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 96);
            }
        }

        public Evergine.Mathematics.Vector4 Parameters_ProximityLightCenterColorOverride
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector4>(112);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 112);
            }
        }

        public Evergine.Mathematics.Vector4 Parameters_ProximityLightMiddleColorOverride
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector4>(128);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 128);
            }
        }

        public Evergine.Mathematics.Vector4 Parameters_ProximityLightOuterColorOverride
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector4>(144);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 144);
            }
        }

        public float Parameters_Metallic
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(160);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 160);
            }
        }

        public float Parameters_Smoothness
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(164);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 164);
            }
        }

        public Evergine.Mathematics.Vector2 Parameters_Tiling
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector2>(176);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 176);
            }
        }

        public Evergine.Mathematics.Vector2 Parameters_Offset
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<Evergine.Mathematics.Vector2>(184);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 184);
            }
        }

        public float Parameters_IridescenceIntensity
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(192);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 192);
            }
        }

        public float Parameters_IridescenceThreshold
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(196);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 196);
            }
        }

        public float Parameters_IridescenceAngle
        {
            get
            {
                return this.material.CBuffers[3].GetBufferData<System.Single>(200);
            }
            set
            {
                this.material.CBuffers[3].SetBufferData(value, 200);
            }
        }

        protected Evergine.Common.Graphics.Texture Internal_Texture
        {
            get
            {
                return this.material.TextureSlots[0].Texture;
            }
            set
            {
                this.material.SetTexture(value, 0);
            }
        }

        protected Evergine.Common.Graphics.Texture Internal_IridescentSpectrumMap
        {
            get
            {
                return this.material.TextureSlots[1].Texture;
            }
            set
            {
                this.material.SetTexture(value, 1);
            }
        }

        public Evergine.Common.Graphics.SamplerState Sampler
        {
            get
            {
                return this.material.SamplerSlots[0].Sampler;
            }
            set
            {
                this.material.SetSampler(value, 0);
            }
        }

        public Evergine.Common.Graphics.SamplerState IridescentSpectrumMapSampler
        {
            get
            {
                return this.material.SamplerSlots[1].Sampler;
            }
            set
            {
                this.material.SetSampler(value, 1);
            }
        }
    }
}
