//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evergine.MRTK.Demo.Effects
{
    using Evergine.Framework.Graphics;


    public class Slate : Evergine.Framework.Graphics.MaterialDecorator
    {

        public Slate(Evergine.Framework.Graphics.Effects.Effect effect) :
                base(new Material(effect))
        {
        }

        public Slate(Evergine.Framework.Graphics.Material material) :
                base(material)
        {
        }

        public Evergine.Mathematics.Matrix4x4 PerDrawCall_WorldViewProj
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<Evergine.Mathematics.Matrix4x4>(0);
            }
            set
            {
                this.material.CBuffers[0].SetBufferData(value, 0);
            }
        }

        public Evergine.Mathematics.Matrix4x4 PerDrawCall_World
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<Evergine.Mathematics.Matrix4x4>(64);
            }
            set
            {
                this.material.CBuffers[0].SetBufferData(value, 64);
            }
        }

        public Evergine.Mathematics.Vector2 Parameters_Tiling
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<Evergine.Mathematics.Vector2>(0);
            }
            set
            {
                this.material.CBuffers[1].SetBufferData(value, 0);
            }
        }

        public Evergine.Mathematics.Vector2 Parameters_Offset
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<Evergine.Mathematics.Vector2>(8);
            }
            set
            {
                this.material.CBuffers[1].SetBufferData(value, 8);
            }
        }

        public Evergine.Mathematics.Matrix4x4 PerCamera_MultiviewViewProj
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<Evergine.Mathematics.Matrix4x4>(0);
            }
            set
            {
                this.material.CBuffers[2].SetBufferData(value, 0);
            }
        }

        public int PerCamera_EyeCount
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<System.Int32>(160);
            }
            set
            {
                this.material.CBuffers[2].SetBufferData(value, 160);
            }
        }

        public Evergine.Common.Graphics.Texture Texture
        {
            get
            {
                return this.material.TextureSlots[0].Texture;
            }
            set
            {
                this.material.SetTexture(value, 0);
            }
        }

        public Evergine.Common.Graphics.SamplerState Sampler
        {
            get
            {
                return this.material.SamplerSlots[0].Sampler;
            }
            set
            {
                this.material.SetSampler(value, 0);
            }
        }
    }
}
