<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Evergine.Packages.Targets" Version="2026.5.19.266-nightly" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\" />
  </ItemGroup>

</Project>
