name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)-rolling

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop

stages:
  - stage: AddonBuild
    displayName: "Build nuget and assets"
    jobs:
      - template: "templates/build.yml"
        parameters:
          buildVersion: "$(Build.BuildNumber)"
          publishEnabled: false
