//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveEngine_MRTK_Demo.Effects
{
    using WaveEngine.Common.Graphics;
    using WaveEngine.Framework.Graphics;
    using WaveEngine.Framework.Graphics.Effects;
    using WaveEngine.Mathematics;
    
    
    public class Slate : WaveEngine.Framework.Graphics.MaterialDecorator
    {
        
        public Slate(WaveEngine.Framework.Graphics.Effects.Effect effect) : 
                base(new Material(effect))
        {
        }
        
        public Slate(WaveEngine.Framework.Graphics.Material material) : 
                base(material)
        {
        }
        
        public WaveEngine.Mathematics.Matrix4x4 Base_WorldViewProj
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<WaveEngine.Mathematics.Matrix4x4>(0);
            }
            set
            {
				this.material.CBuffers[0].SetBufferData(value, 0);
            }
        }
        
        public WaveEngine.Mathematics.Vector2 Matrices_Offset
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<WaveEngine.Mathematics.Vector2>(0);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 0);
            }
        }
        
        public WaveEngine.Mathematics.Vector2 Matrices_Tiling
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<WaveEngine.Mathematics.Vector2>(8);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 8);
            }
        }
        
        public WaveEngine.Common.Graphics.Texture Texture
        {
            get
            {
                return this.material.TextureSlots[0].Texture;
            }
            set
            {
				this.material.SetTexture(value, 0);
            }
        }
        
        public WaveEngine.Common.Graphics.SamplerState Sampler
        {
            get
            {
                return this.material.SamplerSlots[0].Sampler;
            }
            set
            {
				this.material.SetSampler(value, 0);
            }
        }
    }
}
