//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveEngine_MRTK_Demo.Effects
{
    using WaveEngine.Framework.Graphics;


    public class WireframeHolo : WaveEngine.Framework.Graphics.MaterialDecorator
    {
        
        public WireframeHolo(WaveEngine.Framework.Graphics.Effects.Effect effect) : 
                base(new Material(effect))
        {
        }
        
        public WireframeHolo(WaveEngine.Framework.Graphics.Material material) : 
                base(material)
        {
        }
        
        public WaveEngine.Mathematics.Matrix4x4 Base_WorldViewProj
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<WaveEngine.Mathematics.Matrix4x4>(0);
            }
            set
            {
				this.material.CBuffers[0].SetBufferData(value, 0);
            }
        }
        
        public WaveEngine.Mathematics.Matrix4x4 Base_World
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<WaveEngine.Mathematics.Matrix4x4>(64);
            }
            set
            {
				this.material.CBuffers[0].SetBufferData(value, 64);
            }
        }
        
        public WaveEngine.Mathematics.Vector3 Matrices_Color
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<WaveEngine.Mathematics.Vector3>(0);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 0);
            }
        }
        
        public WaveEngine.Mathematics.Vector3 Matrices_EdgeColor
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<WaveEngine.Mathematics.Vector3>(16);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 16);
            }
        }
        
        public float Matrices_EdgeWidth
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<System.Single>(12);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 12);
            }
        }
        
        public float Matrices_EdgeSmooth
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<System.Single>(28);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 28);
            }
        }
        
        public WaveEngine.Mathematics.Vector3 Matrices_TPos
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<WaveEngine.Mathematics.Vector3>(32);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 32);
            }
        }
    }
}
