// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Evergine.MRTK
{
    public sealed class MRTKResourceIDs
    {
        public sealed class Materials
        {
            public sealed class BoundingBox
            {

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlue.wemt) </summary>
                public static readonly Guid BoundingBoxHandleBlue = new Guid("9adff77b-f6b6-4683-bf28-243fafea5436");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlueGrabbed.wemt) </summary>
                public static readonly Guid BoundingBoxHandleBlueGrabbed = new Guid("7c6dfc11-0f01-4d22-bfc9-bc5ca4fae227");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisual.wemt) </summary>
                public static readonly Guid BoundingBoxVisual = new Guid("76254053-dba8-4ecd-8ffd-2989ae519c06");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisualGrabbed.wemt) </summary>
                public static readonly Guid BoundingBoxVisualGrabbed = new Guid("0852af68-ed44-4dd5-bebb-05c15449d498");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxWireframe.wemt) </summary>
                public static readonly Guid BoundingBoxWireframe = new Guid("d04c6b19-b181-4798-8052-73388883abfe");
            }

            public sealed class Buttons
            {
                /// <summary> Asset Path (XRV/Materials/Buttons/ButtonPrimary.wemt) </summary>
                public static readonly Guid ButtonPrimary = new Guid("ce1f6bc9-39ac-4a0a-a913-07963f7342f5");
            }

            public static Guid HolographicButtonContentCageProximity = new Guid("876d9b5c-5016-4796-8473-92a19a5d244c");
        }

        public sealed class Prefabs
        {
            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_FaceScaleHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_FaceScaleHandle_weprefab = new Guid("caa9ea87-b38e-4677-86fb-87ef1cb99838");

            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_RotateHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_RotateHandle_weprefab = new Guid("5e18a808-fd7d-49f9-8187-d9256af252c7");

            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_ScaleHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_ScaleHandle_weprefab = new Guid("ae0e37ce-4928-42ef-970e-a4b1e547f4ea");

            /// <summary> Asset Path (MRTK\Prefabs\ListView.weprefab.weprf) </summary>
            public static readonly Guid ListView_weprefab = new Guid("06d4c0d7-ce72-4657-a123-b25940bf1def");

            public static Guid PressableButtonPlated = new Guid("dabe9073-b1d1-42c5-99b9-ebc0cb4a7430");
        }

        public sealed class RenderLayers
        {
            /// <summary> Asset Path (MRTK/RenderLayers/ScrollContent.werl) </summary>
            public static readonly Guid ScrollContent = new Guid("0d6c4db4-0478-4c3f-8891-2628bf6dfa97");

            /// <summary> Asset Path (MRTK/RenderLayers/ScrollSelection.werl) </summary>
            public static readonly Guid ScrollSelection = new Guid("709bcd4f-6533-43c2-ac6e-42cbc2f76a83");

            /// <summary> Asset Path (MRTK/RenderLayers/ScrollView.werl) </summary>
            public static readonly Guid ScrollView = new Guid("c74ede39-339e-4a01-a495-087626295af3");
        }
    }
}
