// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Evergine.MRTK
{
    public sealed class MRTKResourceIDs
    {
        public sealed class Effects
        {
            /// <summary> Asset Path (MRTK/Effects/HoloGraphic.wefx) </summary>
            public static readonly Guid HoloGraphic = new Guid("4f7e4c24-e83c-4350-9cd4-511fb2199cf4");

            /// <summary> Asset Path (MRTK/Effects/HoloHandsLocal.wefx) </summary>
            public static readonly Guid HoloHandsLocal = new Guid("b7b6076f-e298-45cf-babc-a8316996f359");
        }

        public sealed class Materials
        {
            public sealed class BoundingBox
            {
                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlue.wemt) </summary>
                public static readonly Guid BoundingBoxHandleBlue = new Guid("9adff77b-f6b6-4683-bf28-243fafea5436");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlueGrabbed.wemt) </summary>
                public static readonly Guid BoundingBoxHandleBlueGrabbed = new Guid("7c6dfc11-0f01-4d22-bfc9-bc5ca4fae227");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisual.wemt) </summary>
                public static readonly Guid BoundingBoxVisual = new Guid("76254053-dba8-4ecd-8ffd-2989ae519c06");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisualGrabbed.wemt) </summary>
                public static readonly Guid BoundingBoxVisualGrabbed = new Guid("0852af68-ed44-4dd5-bebb-05c15449d498");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxWireframe.wemt) </summary>
                public static readonly Guid BoundingBoxWireframe = new Guid("d04c6b19-b181-4798-8052-73388883abfe");

                /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlueFocused.wemt) </summary>
                public static readonly Guid BoundingBoxHandleBlueFocused = new Guid("8e30ffce-70db-48f2-b3e1-a5737b0530fc");
            }

            public sealed class Buttons
            {
                /// <summary> Asset Path (XRV/Materials/Buttons/ButtonPrimary.wemt) </summary>
                public static readonly Guid ButtonPrimary = new Guid("ce1f6bc9-39ac-4a0a-a913-07963f7342f5");
            }

            public sealed class PinchSlider
            {
                /// <summary> Asset Path (MRTK/Materials/PinchSlider/PinchSlider_Thumb.wemt) </summary>
                public static readonly Guid PinchSlider_Thumb = new Guid("207c3402-9a1e-43ed-a8a1-11dabe70811d");

                /// <summary> Asset Path (MRTK/Materials/PinchSlider/PinchSlider_Track.wemt) </summary>
                public static readonly Guid PinchSlider_Track = new Guid("7c71e125-9173-449d-a0ab-4771ad204dd5");
            }

            public sealed class Scrolling
            {

                /// <summary> Asset Path (MRTK/Materials/Scrolling/ScrollBackground.wemt) </summary>
                public static readonly Guid ScrollBackground = new Guid("f478b4e6-db00-44f4-a529-3126487183ea");

                /// <summary> Asset Path (MRTK/Materials/Scrolling/ScrollHeader.wemt) </summary>
                public static readonly Guid ScrollHeader = new Guid("ff78b4e6-db00-44f4-a529-3126487183ea");

                /// <summary> Asset Path (MRTK/Materials/Scrolling/ScrollViewerBar.wemt) </summary>
                public static readonly Guid ScrollViewerBar = new Guid("09b7e0f4-19dc-4643-909b-a3494e81343c");

                /// <summary> Asset Path (MRTK/Materials/Scrolling/ScrollViewerSelection.wemt) </summary>
                public static readonly Guid ScrollViewerSelection = new Guid("09f7e0f4-19dc-4643-909b-a3494e81343c");

                /// <summary> Asset Path (MRTK/Materials/Scrolling/ScrollViewerShadow.wemt) </summary>
                public static readonly Guid ScrollViewerShadow = new Guid("98337cd0-8fcc-40f9-953f-b5d5abe34ebf");
            }

            public static Guid HolographicButtonContentCageProximity = new Guid("876d9b5c-5016-4796-8473-92a19a5d244c");

            /// <summary> Asset Path (MRTK/Materials/loadingMat.wemt) </summary>
            public static readonly Guid loadingMat = new Guid("00fd8a25-0cdd-40ad-b39d-12608e78194e");
        }

        public sealed class Prefabs
        {
            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_FaceScaleHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_FaceScaleHandle_weprefab = new Guid("caa9ea87-b38e-4677-86fb-87ef1cb99838");

            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_RotateHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_RotateHandle_weprefab = new Guid("5e18a808-fd7d-49f9-8187-d9256af252c7");

            /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_ScaleHandle.weprefab.weprf) </summary>
            public static readonly Guid BoundingBox_ScaleHandle_weprefab = new Guid("ae0e37ce-4928-42ef-970e-a4b1e547f4ea");

            /// <summary> Asset Path (MRTK/Prefabs/ListView.weprefab.weprf) </summary>
            public static readonly Guid ListView_weprefab = new Guid("9502a182-b61a-4cb2-b320-1d0d2f4ee595");

            /// <summary> Asset Path (MRTK/Prefabs/PressableButtonPlated.weprefab.weprf) </summary>
            public static readonly Guid PressableButtonPlated = new Guid("dabe9073-b1d1-42c5-99b9-ebc0cb4a7430");

            /// <summary> Asset Path (MRTK/Prefabs/ScrollView.weprefab.weprf) </summary>
            public static readonly Guid ScrollView_weprefab = new Guid("6951d88e-98e7-454c-b22f-9e9e1faf4d79");

            public sealed class InputSystem
            {

                public sealed class Controllers
                {

                    /// <summary> Asset Path (MRTK/Prefabs/InputSystem/Controllers/DefaultLeftArticulatedHand.weprefab.weprf) </summary>
                    public static readonly Guid DefaultLeftArticulatedHand_weprefab = new Guid("c540649c-6d32-469b-a68b-a01fcae320cd");

                    /// <summary> Asset Path (MRTK/Prefabs/InputSystem/Controllers/DefaultLeftPhysicalController.weprefab.weprf) </summary>
                    public static readonly Guid DefaultLeftPhysicalController_weprefab = new Guid("d1ef1d0b-c616-4f69-97b3-f4496081df5c");

                    /// <summary> Asset Path (MRTK/Prefabs/InputSystem/Controllers/DefaultRightArticulatedHand.weprefab.weprf) </summary>
                    public static readonly Guid DefaultRightArticulatedHand_weprefab = new Guid("825f028f-628b-4f5e-afe1-ceb27836f1de");

                    /// <summary> Asset Path (MRTK/Prefabs/InputSystem/Controllers/DefaultRightPhysicalController.weprefab.weprf) </summary>
                    public static readonly Guid DefaultRightPhysicalController_weprefab = new Guid("99fd4963-c4c6-498d-92d2-2afcecc75d57");
                }

                public sealed class Pointers
                {

                    /// <summary> Asset Path (MRTK/Prefabs/InputSystem/Pointers/NearPointer.weprefab.weprf) </summary>
                    public static readonly Guid NearPointer_weprefab = new Guid("82b58835-45e6-4dac-b91b-a75cd0bddeab");
                }
            }
        }

        public sealed class RenderLayers
        {
            /// <summary> Asset Path (MRTK/RenderLayers/ScrollContent.werl) </summary>
            public static readonly Guid ScrollContent = new Guid("0d6c4db4-0478-4c3f-8891-2628bf6dfa97");

            /// <summary> Asset Path (MRTK/RenderLayers/ScrollSelection.werl) </summary>
            public static readonly Guid ScrollSelection = new Guid("709bcd4f-6533-43c2-ac6e-42cbc2f76a83");

            /// <summary> Asset Path (MRTK/RenderLayers/ScrollView.werl) </summary>
            public static readonly Guid ScrollView = new Guid("c74ede39-339e-4a01-a495-087626295af3");
        }
    }
}
